### ISSUE TITLE
Couldn't find any versions for "flatmap-stream" that matches "0.1.1"

### ISSUE THREAD

**Issue by nshki** [netlify/create-react-app-lambda#14]
Running `yarn` with a newly cloned repo prompts a manual selection for the "event-stream" package and also is unable to find version 0.1.1 for "flatmap-stream".

Console output:
```
? Please choose a version of "event-stream" from this list: 4.0.1
Couldn't find any versions for "flatmap-stream" that matches "0.1.1"
? Please choose a version of "flatmap-stream" from this list: 0.0.1-security
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/flatmap-stream/-/flatmap-stream-0.1.1.tgz: Request failed \"404 Not Found\"".
```

**Comment by visuallization** [comment]
As fas as I understand this is because of malicious code. flatmap-stream > 0.1.0 is affected.
Check out this issue here: https://github.com/dominictarr/event-stream/issues/116#issuecomment-441749105

**Comment by visuallization** [comment]
kylemcd created a PR to fix this issue. @sw-yx or any of the maintainers please merge: https://github.com/netlify/create-react-app-lambda/pull/16

**Comment by sw-yx** [comment]
thank you all, and thanks @kylemcd for the fix!
