### ISSUE TITLE
Chuck Norris Jokes are inappropriate

### ISSUE THREAD

**Issue by donavon** [netlify/create-react-app-lambda#22]
I know that the content is out of your control, but you may want to consider using a different free API service other than https://api.chucknorris.io for your examples. Many of the "jokes" are inappropriate, or are in bad taste. I'm assuming that a company such as Netlify doesn't want to be associated with this.

I almost hate posting this, but here's an example:

> Whenever Chuck Norris gets a massage, he gives the female masseuse a happy ending.

**Comment by donavon** [comment]
May I suggest a random dog photo using https://dog.ceo/api/breeds/image/random ?

**Comment by sw-yx** [comment]
huh. never saw that before. sad. happy to do this. another candidate is https://icanhazdadjoke.com/api which seems reasonably clean.

**Comment by sw-yx** [comment]
(am busy with confs right now so not gonna do it right away but happy to take pr's)
