### ISSUE TITLE
hyperledger error

### ISSUE THREAD

**Issue by Akrom1996** [netlify/create-react-app-lambda#23]
Hello everyone.
I created web-site using yo. after "npm start" command server is working everything is ok but when I am going to add any participant I get "Error: 504 - Gateway Timeout" this error on web page. in the console I get "[HPM] Error occurred while trying to proxy request /api/Consumer from localhost:4200 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)"

Thank you in advance for any advices

**Comment by sw-yx** [comment]
i dont understand what you wrote. are you on the right repo? what do you mean by hyperledger error? what do you mean when you “add participant”?

**Comment by Akrom1996** [comment]
Hyperledger composer-rest-server error.

пн, 29 апр. 2019 г., 12:56 swyx <notifications@github.com>:
