### ISSUE TITLE
No setupProxy.js file in repo?

### ISSUE THREAD

**Issue by MrToph** [netlify/create-react-app-lambda#29]
The README mentions a `setupProxy.js` file and links to [the advanced proxy setup guide of CRA](https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development#configuring-the-proxy-manually) (link could be updated, it links to an out-dated one).

But there is no `src/setupProxy.js` file. Am I missing something or is this file just missing?

**Comment by MrToph** [comment]
I just saw that it was deleted [by this commit](https://github.com/netlify/create-react-app-lambda/commit/eb77fe87e6431d2e3497cb13f29f4a2690795763).

I can't tell the reason from the commit, maybe @sw-yx can help?

**Comment by juliankohlman** [comment]
@MrToph I think it's causing problems with `react-scripts` specifically the `start` script.

**Comment by sw-yx** [comment]
here, i'm going to update the docs: https://github.com/netlify/create-react-app-lambda/pull/30

sorry ive let this get out of date in the churn since netlify dev
